const data = [
  {
    cost: 117,
    area: 'Valenzuela',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 122,
    area: 'Mysore',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 122,
    area: 'Vadodara',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 126,
    area: 'Bhopal',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 133,
    area: 'Alexandria',
    country: 'Egypt',
    continent: 'Africa',
  },
  {
    cost: 142,
    area: 'Indore',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 143,
    area: 'Bhubaneswar',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 143,
    area: 'Surat',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 144,
    area: 'Medan',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 148,
    area: 'Visakhapatnam',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 150,
    area: 'Lucknow (Lakhnau)',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 151,
    area: 'Nagpur',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 156,
    area: 'Thiruvananthapuram',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 158,
    area: 'Jaipur',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 163,
    area: 'Coimbatore',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 166,
    area: 'Cairo',
    country: 'Egypt',
    continent: 'Africa',
  },
  {
    cost: 174,
    area: 'Mangalore',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 175,
    area: 'Nis',
    country: 'Serbia',
    continent: 'Europe',
  },
  {
    cost: 178,
    area: 'Kathmandu',
    country: 'Nepal',
    continent: 'Asia',
  },
  {
    cost: 185,
    area: 'Bandung',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 186,
    area: 'Yogyakarta',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 191,
    area: 'Ahmedabad',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 191,
    area: 'Navi Mumbai',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 193,
    area: 'Kochi',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 198,
    area: 'Chandigarh',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 200,
    area: 'Noida',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 202,
    area: 'Dnipropetrovsk',
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    cost: 204,
    area: 'Lahore',
    country: 'Pakistan',
    continent: 'Asia',
  },
  {
    cost: 206,
    area: 'Bursa',
    country: 'Turkey',
    continent: 'Middle East',
  },
  {
    cost: 209,
    area: 'Dhaka',
    country: 'Bangladesh',
    continent: 'Asia',
  },
  {
    cost: 209,
    area: 'Craiova',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 209,
    area: 'Davao',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 209,
    area: 'Kuching',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 210,
    area: 'Hyderabad',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 217,
    area: 'Chennai',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 219,
    area: 'Antalya',
    country: 'Turkey',
    continent: 'Europe',
  },
  {
    cost: 220,
    area: 'Puebla',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 223,
    area: 'Burgas',
    country: 'Bulgaria',
    continent: 'Europe',
  },
  {
    cost: 223,
    area: 'Hermosillo',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 226,
    area: 'Tunis',
    country: 'Tunisia',
    continent: 'Africa',
  },
  {
    cost: 227,
    area: 'Oradea',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 227,
    area: 'Cali',
    country: 'Colombia',
    continent: 'South America',
  },
  {
    cost: 228,
    area: 'Karachi',
    country: 'Pakistan',
    continent: 'Asia',
  },
  {
    cost: 228,
    area: 'Novi Sad',
    country: 'Serbia',
    continent: 'Europe',
  },
  {
    cost: 231,
    area: 'Merida',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 232,
    area: 'Kampala',
    country: 'Uganda',
    continent: 'Africa',
  },
  {
    cost: 234,
    area: 'Plovdiv',
    country: 'Bulgaria',
    continent: 'Europe',
  },
  {
    cost: 237,
    area: 'Banja Luka',
    country: 'Bosnia',
    continent: 'And Herzegovina Europe',
  },
  {
    cost: 237,
    area: 'Kolkata',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 238,
    area: 'Quezon City',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 243,
    area: 'Ankara',
    country: 'Turkey',
    continent: 'Middle East',
  },
  {
    cost: 243,
    area: 'Pune',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 247,
    area: 'Lviv',
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    cost: 248,
    area: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 249,
    area: 'Osijek',
    country: 'Croatia',
    continent: 'Europe',
  },
  {
    cost: 253,
    area: 'Goa',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 253,
    area: 'Kharkiv',
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    cost: 258,
    area: 'Sibiu',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 263,
    area: 'Surabaya',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 263,
    area: 'Algiers',
    country: 'Algeria',
    continent: 'Africa',
  },
  {
    cost: 266,
    area: 'Varna',
    country: 'Bulgaria',
    continent: 'Europe',
  },
  {
    cost: 268,
    area: 'Islamabad',
    country: 'Pakistan',
    continent: 'Middle East',
  },
  {
    cost: 271,
    area: 'Izmir',
    country: 'Turkey',
    continent: 'Middle East',
  },
  {
    cost: 282,
    area: 'Arad',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 283,
    area: 'Skopje',
    country: 'Macedonia',
    continent: 'Europe',
  },
  {
    cost: 284,
    area: 'Thane',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 286,
    area: 'Chisinau',
    country: 'Moldova',
    continent: 'Europe',
  },
  {
    cost: 286,
    area: 'Yerevan',
    country: 'Armenia',
    continent: 'Asia',
  },
  {
    cost: 286,
    area: 'Pristina',
    country: 'Kosovo',
    continent: '(Disputed Territory) Europe',
  },
  {
    cost: 287,
    area: 'Patras',
    country: 'Greece',
    continent: 'Europe',
  },
  {
    cost: 291,
    area: 'Queretaro',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 294,
    area: 'Caracas',
    country: 'Venezuela',
    continent: 'South America',
  },
  {
    cost: 295,
    area: 'Baku',
    country: 'Azerbaijan',
    continent: 'Asia',
  },
  {
    cost: 297,
    area: 'Delhi',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 298,
    area: 'Bangalore',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 299,
    area: 'Cancun',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 300,
    area: 'Fortaleza',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 302,
    area: 'Colombo',
    country: 'Sri',
    continent: 'Lanka Africa',
  },
  {
    cost: 304,
    area: 'Brasov',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 304,
    area: 'Tirana',
    country: 'Albania',
    continent: 'Europe',
  },
  {
    cost: 309,
    area: 'Guadalajara',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 309,
    area: 'Sarajevo',
    country: 'Bosnia',
    continent: 'And Herzegovina Europe',
  },
  {
    cost: 312,
    area: 'Odesa',
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    cost: 316,
    area: 'Debrecen',
    country: 'Hungary',
    continent: 'Europe',
  },
  {
    cost: 317,
    area: 'Cuenca',
    country: 'Ecuador',
    continent: 'South America',
  },
  {
    cost: 318,
    area: 'Kaohsiung',
    country: 'Taiwan',
    continent: 'Asia',
  },
  {
    cost: 320,
    area: 'Kota Kinabalu',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 322,
    area: 'Iasi',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 324,
    area: 'Tbilisi',
    country: 'Georgia',
    continent: 'Asia',
  },
  {
    cost: 326,
    area: 'Penang',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 327,
    area: 'Asuncion',
    country: 'Paraguay',
    continent: 'South America',
  },
  {
    cost: 328,
    area: 'Ostrava',
    country: 'Czech',
    continent: 'Republic Europe',
  },
  {
    cost: 329,
    area: 'Timisoara',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 330,
    area: 'Tijuana',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 335,
    area: 'Gurgaon',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 339,
    area: 'Podgorica',
    country: 'Montenegro',
    continent: 'Europe',
  },
  {
    cost: 344,
    area: 'Minsk',
    country: 'Belarus',
    continent: 'Europe',
  },
  {
    cost: 346,
    area: 'Selangor',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 346,
    area: 'Ulaanbaatar',
    country: 'Mongolia',
    continent: 'Asia',
  },
  {
    cost: 347,
    area: 'Larnaca',
    country: 'Cyprus',
    continent: 'Europe',
  },
  {
    cost: 348,
    area: 'Nizhny Novgorod',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 352,
    area: 'Monterrey',
    country: 'Mexico',
    continent: 'South America',
  },
  {
    cost: 352,
    area: 'Puerto Vallarta',
    country: 'Mexico',
    continent: 'South America',
  },
  {
    cost: 353,
    area: 'Thessaloniki',
    country: 'Greece',
    continent: 'Europe',
  },
  {
    cost: 355,
    area: 'Klaipeda',
    country: 'Lithuania',
    continent: 'Europe',
  },
  {
    cost: 358,
    area: 'Almaty',
    country: 'Kazakhstan',
    continent: 'Asia',
  },
  {
    cost: 362,
    area: 'Cebu',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 362,
    area: 'Kigali',
    country: 'Rwanda',
    continent: 'Africa',
  },
  {
    cost: 365,
    area: 'Johor Bahru',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 367,
    area: 'Havana',
    country: 'Cuba',
    continent: 'North America',
  },
  {
    cost: 370,
    area: 'Chiang Mai',
    country: 'Thailand',
    continent: 'Asia',
  },
  {
    cost: 371,
    area: 'Novosibirsk',
    country: 'Russia',
    continent: 'Asia',
  },
  {
    cost: 373,
    area: 'Rostov-na-donu',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 373,
    area: 'Recife',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 375,
    area: 'Nairobi',
    country: 'Kenya',
    continent: 'Africa',
  },
  {
    cost: 375,
    area: 'Belgrade',
    country: 'Serbia',
    continent: 'Europe',
  },
  {
    cost: 375,
    area: 'Braga',
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    cost: 375,
    area: 'Rijeka',
    country: 'Croatia',
    continent: 'Europe',
  },
  {
    cost: 377,
    area: 'Medellin',
    country: 'Colombia',
    continent: 'South America',
  },
  {
    cost: 377,
    area: 'Petaling Jaya',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 378,
    area: 'Katowice',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 378,
    area: 'Kaunas',
    country: 'Lithuania',
    continent: 'Europe',
  },
  {
    cost: 379,
    area: 'Yekaterinburg',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 380,
    area: 'Kiev',
    country: 'Ukraine',
    continent: 'Europe',
  },
  {
    cost: 381,
    area: 'Santo Domingo',
    country: 'Dominican',
    continent: 'Republic North America',
  },
  {
    cost: 384,
    area: 'Belo Horizonte',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 386,
    area: 'Curitiba',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 387,
    area: 'Ad Dammam',
    country: 'Saudi',
    continent: 'Arabia Middle East',
  },
  {
    cost: 389,
    area: 'Chengdu',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 389,
    area: 'Szczecin',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 390,
    area: 'San Salvador',
    country: 'El',
    continent: 'Salvador North America',
  },
  {
    cost: 391,
    area: 'Lodz',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 391,
    area: 'Kazan',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 396,
    area: 'Sofia',
    country: 'Bulgaria',
    continent: 'Europe',
  },
  {
    cost: 397,
    area: 'Taichung',
    country: 'Taiwan',
    continent: 'Asia',
  },
  {
    cost: 397,
    area: 'Olomouc',
    country: 'Czech',
    continent: 'Republic Europe',
  },
  {
    cost: 411,
    area: 'Rabat',
    country: 'Morocco',
    continent: 'Africa',
  },
  {
    cost: 414,
    area: 'Guayaquil',
    country: 'Ecuador',
    continent: 'South America',
  },
  {
    cost: 415,
    area: 'Cluj-Napoca',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 420,
    area: 'Split',
    country: 'Croatia',
    continent: 'Europe',
  },
  {
    cost: 423,
    area: 'Bogota',
    country: 'Colombia',
    continent: 'South America',
  },
  {
    cost: 425,
    area: 'Irbil',
    country: 'Iraq',
    continent: 'Middle East',
  },
  {
    cost: 426,
    area: 'Port Elizabeth',
    country: 'South',
    continent: 'Africa Africa',
  },
  {
    cost: 427,
    area: 'Athens',
    country: 'Greece',
    continent: 'Europe',
  },
  {
    cost: 428,
    area: 'Bucharest',
    country: 'Romania',
    continent: 'Europe',
  },
  {
    cost: 429,
    area: 'Quito',
    country: 'Ecuador',
    continent: 'South America',
  },
  {
    cost: 431,
    area: 'Campinas',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 435,
    area: 'Harare',
    country: 'Zimbabwe',
    continent: 'Africa',
  },
  {
    cost: 435,
    area: 'Santa Cruz',
    country: 'Bolivia',
    continent: 'South America',
  },
  {
    cost: 438,
    area: 'Istanbul',
    country: 'Turkey',
    continent: 'Europe',
  },
  {
    cost: 440,
    area: 'Jeddah (Jiddah)',
    country: 'Saudi',
    continent: 'Arabia Middle East',
  },
  {
    cost: 441,
    area: 'Tartu',
    country: 'Estonia',
    continent: 'Europe',
  },
  {
    cost: 445,
    area: 'Hanoi',
    country: 'Vietnam',
    continent: 'Asia',
  },
  {
    cost: 445,
    area: 'Amman',
    country: 'Jordan',
    continent: 'Middle East',
  },
  {
    cost: 445,
    area: 'Coimbra',
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    cost: 446,
    area: 'Gdynia',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 447,
    area: 'Phuket',
    country: 'Thailand',
    continent: 'Asia',
  },
  {
    cost: 451,
    area: 'Baghdad',
    country: 'Iraq',
    continent: 'Middle East',
  },
  {
    cost: 452,
    area: 'Porto Alegre',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 454,
    area: 'Astana',
    country: 'Kazakhstan',
    continent: 'Asia',
  },
  {
    cost: 455,
    area: 'Granada',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 461,
    area: 'Florianopolis',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 461,
    area: 'Bydgoszcz',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 464,
    area: 'Zaragoza (Saragossa)',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 465,
    area: 'Riga',
    country: 'Latvia',
    continent: 'Europe',
  },
  {
    cost: 470,
    area: 'Zagreb',
    country: 'Croatia',
    continent: 'Europe',
  },
  {
    cost: 472,
    area: 'Poznan',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 474,
    area: 'Guatemala City',
    country: 'Guatemala',
    continent: 'South America',
  },
  {
    cost: 476,
    area: 'Buenos Aires',
    country: 'Argentina',
    continent: 'South America',
  },
  {
    cost: 476,
    area: 'Pretoria',
    country: 'South',
    continent: 'Africa Africa',
  },
  {
    cost: 479,
    area: 'Al Khobar',
    country: 'Saudi',
    continent: 'Arabia Middle East',
  },
  {
    cost: 481,
    area: 'Durban',
    country: 'South',
    continent: 'Africa Africa',
  },
  {
    cost: 493,
    area: 'Kosice',
    country: 'Slovakia',
    continent: 'Europe',
  },
  {
    cost: 502,
    area: 'Casablanca',
    country: 'Morocco',
    continent: 'Africa',
  },
  {
    cost: 503,
    area: 'Riyadh',
    country: 'Saudi',
    continent: 'Arabia Middle East',
  },
  {
    cost: 511,
    area: 'Brasilia',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 522,
    area: 'Suzhou',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 526,
    area: 'Nicosia',
    country: 'Cyprus',
    continent: 'Europe',
  },
  {
    cost: 532,
    area: 'Phnom Penh',
    country: 'Cambodia',
    continent: 'Asia',
  },
  {
    cost: 539,
    area: 'Tallinn',
    country: 'Estonia',
    continent: 'Europe',
  },
  {
    cost: 544,
    area: 'Gdansk',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 545,
    area: 'Mexico City',
    country: 'Mexico',
    continent: 'North America',
  },
  {
    cost: 545,
    area: 'Santiago',
    country: 'Chile',
    continent: 'South America',
  },
  {
    cost: 547,
    area: 'Vilnius',
    country: 'Lithuania',
    continent: 'Europe',
  },
  {
    cost: 547,
    area: 'Funchal',
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    cost: 547,
    area: 'Lima',
    country: 'Peru',
    continent: 'South America',
  },
  {
    cost: 548,
    area: 'Kuala Lumpur',
    country: 'Malaysia',
    continent: 'Asia',
  },
  {
    cost: 549,
    area: 'Quebec City',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 551,
    area: 'Lublin',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 551,
    area: 'Santa Cruz De Tenerife',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 552,
    area: 'Budapest',
    country: 'Hungary',
    continent: 'Europe',
  },
  {
    cost: 555,
    area: 'Krakow (Cracow)',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 567,
    area: 'Maputo',
    country: 'Mozambique',
    continent: 'Africa',
  },
  {
    cost: 568,
    area: 'Pattaya',
    country: 'Thailand',
    continent: 'Asia',
  },
  {
    cost: 569,
    area: 'Moncton',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 574,
    area: 'Springfield',
    country: 'MO',
    continent: 'North America',
  },
  {
    cost: 574,
    area: 'Ho Chi Minh City',
    country: 'Vietnam',
    continent: 'Asia',
  },
  {
    cost: 588,
    area: 'Brno',
    country: 'Czech',
    continent: 'Republic Europe',
  },
  {
    cost: 589,
    area: 'San Jose',
    country: 'Costa Rica',
    continent: 'North America',
  },
  {
    cost: 591,
    area: 'Jakarta',
    country: 'Indonesia',
    continent: 'Asia',
  },
  {
    cost: 600,
    area: 'Wroclaw',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 602,
    area: 'Gatineau',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 606,
    area: 'Naples',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 609,
    area: 'Tehran',
    country: 'Iran',
    continent: 'Middle East',
  },
  {
    cost: 609,
    area: 'Manila',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 613,
    area: 'Las Palmas',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 616,
    area: 'Saint Petersburg',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 617,
    area: 'Leipzig',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 629,
    area: 'Valencia',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 630,
    area: 'Ljubljana',
    country: 'Slovenia',
    continent: 'Europe',
  },
  {
    cost: 632,
    area: 'Haifa',
    country: 'Israel',
    continent: 'Middle East',
  },
  {
    cost: 635,
    area: 'Martin',
    country: 'Slovakia',
    continent: 'Europe',
  },
  {
    cost: 637,
    area: 'Porto',
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    cost: 639,
    area: 'Guangzhou',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 642,
    area: 'Sao Paulo',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 646,
    area: 'Montevideo',
    country: 'Uruguay',
    continent: 'South America',
  },
  {
    cost: 646,
    area: 'Sevilla',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 647,
    area: 'Malaga',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 653,
    area: 'Windsor',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 654,
    area: 'Fort Wayne',
    country: 'IN',
    continent: 'North America',
  },
  {
    cost: 656,
    area: 'Derby',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 656,
    area: 'Genoa',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 658,
    area: 'Trieste',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 659,
    area: 'Akron',
    country: 'OH',
    continent: 'North America',
  },
  {
    cost: 660,
    area: 'Rio De Janeiro',
    country: 'Brazil',
    continent: 'South America',
  },
  {
    cost: 660,
    area: 'Taipei',
    country: 'Taiwan',
    continent: 'Asia',
  },
  {
    cost: 671,
    area: 'Dayton',
    country: 'OH',
    continent: 'North America',
  },
  {
    cost: 673,
    area: 'Hanover',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 673,
    area: 'Bergamo',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 679,
    area: 'Bremen',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 686,
    area: 'Augusta',
    country: 'GA',
    continent: 'North America',
  },
  {
    cost: 686,
    area: 'Johannesburg',
    country: 'South',
    continent: 'Africa Africa',
  },
  {
    cost: 686,
    area: "St. John's",
    country: 'NL,',
    continent: 'Canada North America',
  },
  {
    cost: 687,
    area: 'Warsaw',
    country: 'Poland',
    continent: 'Europe',
  },
  {
    cost: 694,
    area: 'Mumbai',
    country: 'India',
    continent: 'Asia',
  },
  {
    cost: 698,
    area: 'Bratislava',
    country: 'Slovakia',
    continent: 'Europe',
  },
  {
    cost: 701,
    area: 'Dresden',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 706,
    area: 'Windhoek',
    country: 'Namibia',
    continent: 'Africa',
  },
  {
    cost: 710,
    area: 'Turin',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 724,
    area: 'Belfast',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 727,
    area: 'Tucson',
    country: 'AZ',
    continent: 'North America',
  },
  {
    cost: 729,
    area: 'Osaka',
    country: 'Japan',
    continent: 'Asia',
  },
  {
    cost: 730,
    area: 'Karlsruhe',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 730,
    area: 'Padova',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 730,
    area: 'Marseille',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 740,
    area: 'Limassol',
    country: 'Cyprus',
    continent: 'Europe',
  },
  {
    cost: 745,
    area: 'Addis Ababa',
    country: 'Ethiopia',
    continent: 'Africa',
  },
  {
    cost: 745,
    area: 'Palma De Mallorca',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 748,
    area: 'Aachen',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 750,
    area: 'Dar Es Salaam',
    country: 'Tanzania',
    continent: 'Africa',
  },
  {
    cost: 751,
    area: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
  },
  {
    cost: 751,
    area: 'London',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 752,
    area: 'Lubbock',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 752,
    area: 'Mobile',
    country: 'AL',
    continent: 'North America',
  },
  {
    cost: 752,
    area: 'Wichita',
    country: 'KS',
    continent: 'North America',
  },
  {
    cost: 754,
    area: 'Lille',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 757,
    area: 'Nottingham',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 758,
    area: 'Little Rock',
    country: 'AR',
    continent: 'North America',
  },
  {
    cost: 759,
    area: 'Fayetteville',
    country: 'AR',
    continent: 'North America',
  },
  {
    cost: 761,
    area: 'Winnipeg',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 762,
    area: 'Graz',
    country: 'Austria',
    continent: 'Europe',
  },
  {
    cost: 762,
    area: 'Montpellier',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 762,
    area: 'Liverpool',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 762,
    area: 'Winston-salem',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 763,
    area: 'Toulouse',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 765,
    area: 'Parma',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 765,
    area: 'Sheffield',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 765,
    area: 'Prague',
    country: 'Czech',
    continent: 'Republic Europe',
  },
  {
    cost: 766,
    area: 'Grenoble',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 766,
    area: 'Nuremberg',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 767,
    area: 'Nanaimo',
    country: 'BC,',
    continent: 'Canada North America',
  },
  {
    cost: 771,
    area: 'Shreveport',
    country: 'LA',
    continent: 'North America',
  },
  {
    cost: 774,
    area: 'Norwich',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 775,
    area: 'Shenzhen',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 776,
    area: 'Muscat',
    country: 'Oman',
    continent: 'Middle East',
  },
  {
    cost: 779,
    area: 'Albuquerque',
    country: 'NM',
    continent: 'North America',
  },
  {
    cost: 779,
    area: 'Lexington',
    country: 'KY',
    continent: 'North America',
  },
  {
    cost: 779,
    area: 'Red Deer',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 780,
    area: 'Turku',
    country: 'Finland',
    continent: 'Europe',
  },
  {
    cost: 784,
    area: 'Newcastle Upon Tyne',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 785,
    area: 'Sioux Falls',
    country: 'SD',
    continent: 'North America',
  },
  {
    cost: 795,
    area: 'Greensboro',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 796,
    area: 'Bologna',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 797,
    area: 'San Juan',
    country: 'Puerto',
    continent: 'Rico North America',
  },
  {
    cost: 800,
    area: 'Thunder Bay',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 800,
    area: 'Bangkok',
    country: 'Thailand',
    continent: 'Asia',
  },
  {
    cost: 808,
    area: 'Coventry',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 810,
    area: 'Oklahoma City',
    country: 'OK',
    continent: 'North America',
  },
  {
    cost: 812,
    area: 'Malta',
    country: 'Malta',
    continent: 'Asia',
  },
  {
    cost: 814,
    area: 'Athens',
    country: 'GA',
    continent: 'North America',
  },
  {
    cost: 815,
    area: 'Montreal',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 819,
    area: 'Aalborg',
    country: 'Denmark',
    continent: 'Europe',
  },
  {
    cost: 822,
    area: 'Makati',
    country: 'Philippines',
    continent: 'Asia',
  },
  {
    cost: 822,
    area: 'Gent',
    country: 'Belgium',
    continent: 'Europe',
  },
  {
    cost: 824,
    area: 'Spokane',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 824,
    area: 'Hamilton',
    country: 'New',
    continent: 'Zealand Oceana',
  },
  {
    cost: 827,
    area: 'Lund',
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    cost: 832,
    area: 'Mannheim',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 835,
    area: 'Kitchener',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 838,
    area: 'Huntsville',
    country: 'AL',
    continent: 'North America',
  },
  {
    cost: 840,
    area: 'Memphis',
    country: 'TN',
    continent: 'North America',
  },
  {
    cost: 843,
    area: 'Hamilton',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 846,
    area: 'Limerick',
    country: 'Ireland',
    continent: 'Europe',
  },
  {
    cost: 848,
    area: 'Chattanooga',
    country: 'TN',
    continent: 'North America',
  },
  {
    cost: 848,
    area: 'Harrisburg',
    country: 'PA',
    continent: 'North America',
  },
  {
    cost: 856,
    area: 'Barrie',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 856,
    area: 'Lyon',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 857,
    area: 'Antwerp',
    country: 'Belgium',
    continent: 'Europe',
  },
  {
    cost: 859,
    area: 'Glasgow',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 865,
    area: 'Cardiff',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 865,
    area: 'Louisville',
    country: 'KY',
    continent: 'North America',
  },
  {
    cost: 866,
    area: 'Cleveland',
    country: 'OH',
    continent: 'North America',
  },
  {
    cost: 867,
    area: 'Lincoln',
    country: 'NE',
    continent: 'North America',
  },
  {
    cost: 868,
    area: 'Uppsala',
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    cost: 872,
    area: 'Malmo',
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    cost: 874,
    area: 'Tulsa',
    country: 'OK',
    continent: 'North America',
  },
  {
    cost: 877,
    area: 'Pensacola',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 881,
    area: 'Guelph',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 882,
    area: 'Tampere',
    country: 'Finland',
    continent: 'Europe',
  },
  {
    cost: 883,
    area: 'Boise',
    country: 'ID',
    continent: 'North America',
  },
  {
    cost: 883,
    area: 'Regina',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 884,
    area: 'Buffalo',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 885,
    area: 'Cape Town',
    country: 'South',
    continent: 'Africa Africa',
  },
  {
    cost: 886,
    area: 'Brampton',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 888,
    area: 'Bakersfield',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 893,
    area: 'Bonn',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 896,
    area: 'Halifax',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 896,
    area: 'Kansas City',
    country: 'MO',
    continent: 'North America',
  },
  {
    cost: 896,
    area: 'Lisbon',
    country: 'Portugal',
    continent: 'Europe',
  },
  {
    cost: 897,
    area: 'Melbourne',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 899,
    area: 'Linz',
    country: 'Austria',
    continent: 'Europe',
  },
  {
    cost: 900,
    area: 'Columbia',
    country: 'SC',
    continent: 'North America',
  },
  {
    cost: 900,
    area: 'Leuven',
    country: 'Belgium',
    continent: 'Europe',
  },
  {
    cost: 903,
    area: 'Birmingham',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 905,
    area: 'Waterloo',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 907,
    area: 'York',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 907,
    area: 'Saskatoon',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 908,
    area: 'Cologne',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 909,
    area: 'Knoxville',
    country: 'TN',
    continent: 'North America',
  },
  {
    cost: 912,
    area: 'Sharjah',
    country: 'United',
    continent: 'Arab Emirates Middle East',
  },
  {
    cost: 915,
    area: 'Las Vegas',
    country: 'NV',
    continent: 'North America',
  },
  {
    cost: 917,
    area: 'Arlington',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 919,
    area: 'Saint Louis',
    country: 'MO',
    continent: 'North America',
  },
  {
    cost: 920,
    area: 'Christchurch',
    country: 'New',
    continent: 'Zealand Oceana',
  },
  {
    cost: 925,
    area: 'Bilbao',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 926,
    area: 'Leeds',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 926,
    area: 'Rochester',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 929,
    area: 'Omaha',
    country: 'NE',
    continent: 'North America',
  },
  {
    cost: 930,
    area: 'Gothenburg',
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    cost: 934,
    area: 'Cairns',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 936,
    area: 'Manama',
    country: 'Bahrain',
    continent: 'Middle East',
  },
  {
    cost: 937,
    area: 'Darmstadt',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 940,
    area: 'Syracuse',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 941,
    area: 'Albany',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 943,
    area: 'Manchester',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 944,
    area: 'Groningen',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 945,
    area: 'Fresno',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 950,
    area: 'Cincinnati',
    country: 'OH',
    continent: 'North America',
  },
  {
    cost: 953,
    area: 'Colorado Springs',
    country: 'CO',
    continent: 'North America',
  },
  {
    cost: 954,
    area: 'Des Moines',
    country: 'IA',
    continent: 'North America',
  },
  {
    cost: 958,
    area: 'Birmingham',
    country: 'AL',
    continent: 'North America',
  },
  {
    cost: 958,
    area: 'Calgary',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 958,
    area: 'Eugene',
    country: 'OR',
    continent: 'North America',
  },
  {
    cost: 961,
    area: 'Hobart',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 965,
    area: 'Edmonton',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 966,
    area: 'Nice',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 970,
    area: 'Ottawa',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 971,
    area: 'Florence',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 973,
    area: 'Exeter',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 974,
    area: 'Fort Myers',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 977,
    area: 'Salem',
    country: 'OR',
    continent: 'North America',
  },
  {
    cost: 981,
    area: 'Aberdeen',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 984,
    area: 'Portsmouth',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 985,
    area: 'Jacksonville',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 986,
    area: 'Accra',
    country: 'Ghana',
    continent: 'Africa',
  },
  {
    cost: 991,
    area: 'Panama City',
    country: 'Panama',
    continent: 'North America',
  },
  {
    cost: 999,
    area: 'College Station',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1006,
    area: 'Grand Rapids',
    country: 'MI',
    continent: 'North America',
  },
  {
    cost: 1010,
    area: 'Southampton',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1017,
    area: 'Phoenix',
    country: 'AZ',
    continent: 'North America',
  },
  {
    cost: 1018,
    area: 'Maastricht',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1019,
    area: 'Surrey',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1020,
    area: 'Madrid',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 1023,
    area: 'Beijing',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 1024,
    area: 'Berlin',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1026,
    area: 'Hamburg',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1026,
    area: 'Manchester',
    country: 'NH',
    continent: 'North America',
  },
  {
    cost: 1027,
    area: 'Bloomington',
    country: 'IN',
    continent: 'North America',
  },
  {
    cost: 1029,
    area: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
  },
  {
    cost: 1041,
    area: 'Moscow',
    country: 'Russia',
    continent: 'Europe',
  },
  {
    cost: 1042,
    area: 'Vancouver',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1044,
    area: 'Burlington',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1054,
    area: 'San Antonio',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1056,
    area: 'Galway',
    country: 'Ireland',
    continent: 'Europe',
  },
  {
    cost: 1057,
    area: 'Edinburgh',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1060,
    area: 'Bellingham',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1063,
    area: 'Arhus',
    country: 'Denmark',
    continent: 'Europe',
  },
  {
    cost: 1064,
    area: 'Kelowna',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1065,
    area: 'Stuttgart',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1066,
    area: 'Salt Lake City',
    country: 'UT',
    continent: 'North America',
  },
  {
    cost: 1068,
    area: 'Beirut',
    country: 'Lebanon',
    continent: 'Middle East',
  },
  {
    cost: 1070,
    area: 'Vienna',
    country: 'Austria',
    continent: 'Europe',
  },
  {
    cost: 1075,
    area: 'Eindhoven',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1077,
    area: 'Rotterdam',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1078,
    area: 'Fort Worth',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1083,
    area: 'Detroit',
    country: 'MI',
    continent: 'North America',
  },
  {
    cost: 1084,
    area: 'Milwaukee',
    country: 'WI',
    continent: 'North America',
  },
  {
    cost: 1084,
    area: 'Columbus',
    country: 'OH',
    continent: 'North America',
  },
  {
    cost: 1085,
    area: 'Durham',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 1086,
    area: 'The Hague (Den Haag)',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1089,
    area: 'Indianapolis',
    country: 'IN',
    continent: 'North America',
  },
  {
    cost: 1092,
    area: 'Brussels',
    country: 'Belgium',
    continent: 'Europe',
  },
  {
    cost: 1099,
    area: 'Reno',
    country: 'NV',
    continent: 'North America',
  },
  {
    cost: 1100,
    area: 'Greenville',
    country: 'SC',
    continent: 'North America',
  },
  {
    cost: 1101,
    area: 'Olympia',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1105,
    area: 'Sliema',
    country: 'Malta',
    continent: 'Europe',
  },
  {
    cost: 1105,
    area: 'Richmond',
    country: 'VA',
    continent: 'North America',
  },
  {
    cost: 1110,
    area: 'Dusseldorf',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1116,
    area: 'Adelaide',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1119,
    area: 'Mississauga',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1124,
    area: 'Tacoma',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1128,
    area: 'Ramat Gan',
    country: 'Israel',
    continent: 'Middle East',
  },
  {
    cost: 1128,
    area: 'Madison',
    country: 'WI',
    continent: 'North America',
  },
  {
    cost: 1132,
    area: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
  },
  {
    cost: 1135,
    area: 'Seoul',
    country: 'South',
    continent: 'Korea Asia',
  },
  {
    cost: 1136,
    area: 'Heidelberg',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1140,
    area: 'Milton Keynes',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1141,
    area: 'Orlando',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1143,
    area: 'Raleigh',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 1143,
    area: 'Virginia Beach',
    country: 'VA',
    continent: 'North America',
  },
  {
    cost: 1148,
    area: 'Frankfurt',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1149,
    area: 'Bath',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1156,
    area: 'Asheville',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 1174,
    area: 'Jerusalem',
    country: 'Israel',
    continent: 'Middle East',
  },
  {
    cost: 1184,
    area: 'Gold Coast',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1192,
    area: 'Pittsburgh',
    country: 'PA',
    continent: 'North America',
  },
  {
    cost: 1216,
    area: 'Stavanger',
    country: 'Norway',
    continent: 'Europe',
  },
  {
    cost: 1221,
    area: 'Cork',
    country: 'Ireland',
    continent: 'Europe',
  },
  {
    cost: 1221,
    area: 'Victoria',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1222,
    area: 'Bristol',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1222,
    area: 'Plano',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1225,
    area: 'Anchorage',
    country: 'AK',
    continent: 'North America',
  },
  {
    cost: 1228,
    area: 'New Orleans',
    country: 'LA',
    continent: 'North America',
  },
  {
    cost: 1229,
    area: 'Utrecht',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1229,
    area: 'Rome',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 1231,
    area: 'Bergen',
    country: 'Norway',
    continent: 'Europe',
  },
  {
    cost: 1231,
    area: 'Newark',
    country: 'NJ',
    continent: 'North America',
  },
  {
    cost: 1233,
    area: 'Saint Paul',
    country: 'MN',
    continent: 'North America',
  },
  {
    cost: 1234,
    area: 'Wellington',
    country: 'New',
    continent: 'Zealand Oceana',
  },
  {
    cost: 1235,
    area: 'Nassau',
    country: 'Bahamas',
    continent: 'North America',
  },
  {
    cost: 1237,
    area: 'Perth',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1237,
    area: 'Helsinki',
    country: 'Finland',
    continent: 'Europe',
  },
  {
    cost: 1240,
    area: 'Charlotte',
    country: 'NC',
    continent: 'North America',
  },
  {
    cost: 1244,
    area: 'Portland',
    country: 'ME',
    continent: 'North America',
  },
  {
    cost: 1249,
    area: 'Reading',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1252,
    area: 'Saint Petersburg',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1279,
    area: 'Burlington',
    country: 'VT',
    continent: 'North America',
  },
  {
    cost: 1281,
    area: 'Shanghai',
    country: 'China',
    continent: 'Asia',
  },
  {
    cost: 1285,
    area: 'Fort Collins',
    country: 'CO',
    continent: 'North America',
  },
  {
    cost: 1285,
    area: 'Tampa',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1287,
    area: 'Hartford',
    country: 'CT',
    continent: 'North America',
  },
  {
    cost: 1294,
    area: 'Trondheim',
    country: 'Norway',
    continent: 'Europe',
  },
  {
    cost: 1297,
    area: 'Everett',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1302,
    area: 'Dallas',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1316,
    area: 'West Palm Beach',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1323,
    area: 'Brisbane',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1323,
    area: 'Sacramento',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 1327,
    area: 'Newcastle',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1330,
    area: 'Bern',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 1331,
    area: 'Norfolk',
    country: 'VA',
    continent: 'North America',
  },
  {
    cost: 1333,
    area: 'Milan',
    country: 'Italy',
    continent: 'Europe',
  },
  {
    cost: 1347,
    area: 'Houston',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1368,
    area: 'Melbourne',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1371,
    area: 'Brighton',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1375,
    area: 'Baltimore',
    country: 'MD',
    continent: 'North America',
  },
  {
    cost: 1375,
    area: 'Canberra',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1382,
    area: 'Ann Arbor',
    country: 'MI',
    continent: 'North America',
  },
  {
    cost: 1382,
    area: 'Stockholm',
    country: 'Sweden',
    continent: 'Europe',
  },
  {
    cost: 1394,
    area: 'Minneapolis',
    country: 'MN',
    continent: 'North America',
  },
  {
    cost: 1400,
    area: 'Atlanta',
    country: 'GA',
    continent: 'North America',
  },
  {
    cost: 1404,
    area: 'Charleston',
    country: 'SC',
    continent: 'North America',
  },
  {
    cost: 1419,
    area: 'Munich',
    country: 'Germany',
    continent: 'Europe',
  },
  {
    cost: 1421,
    area: 'Darwin',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 1433,
    area: 'Toronto',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1434,
    area: 'Auckland',
    country: 'New',
    continent: 'Zealand Oceana',
  },
  {
    cost: 1445,
    area: 'Cambridge',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1451,
    area: 'New Haven',
    country: 'CT',
    continent: 'North America',
  },
  {
    cost: 1458,
    area: 'Nashville',
    country: 'TN',
    continent: 'North America',
  },
  {
    cost: 1469,
    area: 'Philadelphia',
    country: 'PA',
    continent: 'North America',
  },
  {
    cost: 1505,
    area: 'Oslo',
    country: 'Norway',
    continent: 'Europe',
  },
  {
    cost: 1517,
    area: 'Basel',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 1521,
    area: 'Austin',
    country: 'TX',
    continent: 'North America',
  },
  {
    cost: 1536,
    area: 'Paris',
    country: 'France',
    continent: 'Europe',
  },
  {
    cost: 1547,
    area: 'Copenhagen',
    country: 'Denmark',
    continent: 'Europe',
  },
  {
    cost: 1574,
    area: 'Tel Aviv-Yafo',
    country: 'Israel',
    continent: 'Middle East',
  },
  {
    cost: 1577,
    area: 'Fort Lauderdale',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1579,
    area: 'Portland',
    country: 'OR',
    continent: 'North America',
  },
  {
    cost: 1598,
    area: 'Lausanne',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 1616,
    area: 'Lugano',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 1627,
    area: 'Oxford',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 1634,
    area: 'Vancouver',
    country: 'Canada',
    continent: 'North America',
  },
  {
    cost: 1643,
    area: 'Boulder',
    country: 'CO',
    continent: 'North America',
  },
  {
    cost: 1649,
    area: 'Denver',
    country: 'CO',
    continent: 'North America',
  },
  {
    cost: 1679,
    area: 'Long Beach',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 1732,
    area: 'Chicago',
    country: 'IL',
    continent: 'North America',
  },
  {
    cost: 1748,
    area: 'Reykjavik',
    country: 'Iceland',
    continent: 'Europe',
  },
  {
    cost: 1775,
    area: 'Santa Rosa',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 1778,
    area: 'Amsterdam',
    country: 'Netherlands',
    continent: 'Europe',
  },
  {
    cost: 1881,
    area: 'Luxembourg',
    country: 'Luxembourg',
    continent: 'Europe',
  },
  {
    cost: 1889,
    area: 'Arlington',
    country: 'VA',
    continent: 'North America',
  },
  {
    cost: 1891,
    area: 'San Diego',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 1897,
    area: 'Dublin',
    country: 'Ireland',
    continent: 'Europe',
  },
  {
    cost: 1918,
    area: 'Honolulu',
    country: 'HI',
    continent: 'North America',
  },
  {
    cost: 1930,
    area: 'Miami',
    country: 'FL',
    continent: 'North America',
  },
  {
    cost: 1954,
    area: 'Rockville',
    country: 'MD',
    continent: 'North America',
  },
  {
    cost: 1962,
    area: 'Abu Dhabi',
    country: 'United',
    continent: 'Arab Emirates Middle East',
  },
  {
    cost: 1967,
    area: 'Seattle',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 1977,
    area: 'Queens',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 2015,
    area: 'Jersey City',
    country: 'NJ',
    continent: 'North America',
  },
  {
    cost: 2020,
    area: 'Zurich',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 2023,
    area: 'Irvine',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 2036,
    area: 'Bellevue',
    country: 'WA',
    continent: 'North America',
  },
  {
    cost: 2041,
    area: 'Doha',
    country: 'Qatar',
    continent: 'Middle East',
  },
  {
    cost: 2042,
    area: 'Dubai',
    country: 'United',
    continent: 'Arab Emirates Middle East',
  },
  {
    cost: 2090,
    area: 'Sydney',
    country: 'Australia',
    continent: 'Oceana',
  },
  {
    cost: 2099,
    area: 'Los Angeles',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 2182,
    area: 'Santa Barbara',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 2189,
    area: 'Geneva',
    country: 'Switzerland',
    continent: 'Europe',
  },
  {
    cost: 2195,
    area: 'Singapore',
    country: 'Singapore',
    continent: 'Asia',
  },
  {
    cost: 2238,
    area: 'Washington',
    country: 'DC',
    continent: 'North America',
  },
  {
    cost: 2328,
    area: 'Brooklyn',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 2341,
    area: 'London',
    country: 'United',
    continent: 'Kingdom Europe',
  },
  {
    cost: 2403,
    area: 'Berkeley',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 2404,
    area: 'Boston',
    country: 'MA',
    continent: 'North America',
  },
  {
    cost: 2429,
    area: 'Hong Kong',
    country: 'Hong',
    continent: 'Kong Asia',
  },
  {
    cost: 2430,
    area: 'Oakland',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 2498,
    area: 'San Jose',
    country: 'CA',
    continent: 'North America',
  },
  {
    cost: 3054,
    area: 'Manhattan',
    country: 'NY',
    continent: 'North America',
  },
  {
    cost: 3386,
    area: 'Hamilton',
    country: 'Bermuda',
    continent: 'North America',
  },
  {
    cost: 3523,
    area: 'San Francisco',
    country: 'CA',
    continent: 'North America',
  },
];

module.exports = {
  data,
};
